services:
  app:
    image: customer-term-deposits-predictor
    ports:
      - "8888:8888" # Map container's port 8888 to local port 8888
    volumes:
      - .:/home/jovyan/work # Mounts current directory to /home/jovyan/work in the container
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--no-browser", "--allow-root"]
