name: "term-deposit-predictor"

channels:
  - conda-forge
  - plotly
  - defaults
dependencies:
  - pandera=0.21.0
  - python==3.11
  - ipykernel=6.29.5
  - matplotlib=3.9.2
  - nb_conda_kernels=2.5.1
  - pandas=2.2.3
  - scikit-learn=1.5.2
  - requests=2.32.3
  - ipython=8.29.0
  - graphviz=12.0.0
  - python-graphviz=0.20.3
  - plotly=5.24.1
  - panel=1.5.4
  - altair-all=5.4.1
  - vega_datasets=0.9.0
  - pip
  - pip:
      - mglearn==0.2.0
      - graphviz==0.20.3
      - nbformat==5.10.4
      - nbclient==0.10.0
      - transformers==4.46.3
      - datasets==3.1.0
      - ultralytics==8.3.34
      - psutil==6.1.0