name: "group3"

channels:
  - conda-forge
  - pytorch
  - anaconda
  - plotly
  - defaults
dependencies:
  - python==3.12
  - ipykernel
  - matplotlib
  - pandas
  - nb_conda_kernels
  - scikit-learn>=1.5.1
  - requests
  - ipython
  - graphviz
  - python-graphviz
  - jinja2
  - lightgbm
  - torchvision
  - torchaudio
  - pytorch
  - autograd
  - plotly
  - panel
  - watchfiles
  - wikipedia
  - altair-all
  - vega_datasets # Example data
  - pip>=24.2
  - pip:
      - mglearn
      - otter-grader
      - graphviz
      - nbformat
      - nbclient
      - transformers
      - datasets
      - ultralytics
      - psutil>=5.7.2